# Generated by Django 4.2.5 on 2023-09-29 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("d", "Daily"),
                            ("w", "Weekly"),
                            ("m", "Monthly"),
                            ("q", "Quarterly"),
                            ("y", "Yearly"),
                        ],
                        default="m",
                        help_text="Frequency of expense",
                        max_length=1,
                    ),
                ),
                ("service_provider", models.CharField(max_length=255)),
                ("tier", models.CharField(blank=True, max_length=255, null=True)),
                ("is_common", models.BooleanField(default=True, editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("d", "Daily"),
                            ("w", "Weekly"),
                            ("m", "Monthly"),
                            ("q", "Quarterly"),
                            ("y", "Yearly"),
                        ],
                        default="m",
                        help_text="Frequency of expense",
                        max_length=1,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_monthly_expenses",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("surplus", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("expenses", models.ManyToManyField(to="budget.userexpense")),
                ("income_sources", models.ManyToManyField(to="budget.incomesource")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
