# Generated by Django 4.2.6 on 2023-11-01 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonexpense",
            name="service_provider",
        ),
        migrations.AlterField(
            model_name="budget",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
