# Generated by Django 4.2.6 on 2023-11-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_remove_commonexpense_service_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonexpense",
            name="service_provider",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
